blank_issues_enabled: false
contact_links:
  - name: TP-Link Forums
    url: https://community.tp-link.com/en/business/forum/582
    about: For issues related to the Omada Controller software, use the forums!  I am not a developer of the Omada Controller software and do not have access to the source code.
