name: Feature Request
description: For feature request related to this Docker image only.
title: '[Feature]: '
assignees:
  - mbentley
body:
  - type: markdown
    attributes:
      value: |
        ## Read Me First!

        You are about to report a bug you found related to the packaging or function of this Docker image, not the Controller software itself. If you have a problem with the software that is not related to this Docker image, I would suggest you file an issue on the [TP-Link community forums](https://community.tp-link.com/en/business/forum/582).  If you're not sure if it is a problem with the Docker image or the software, feel free to file an issue here and I can assist you with determining where the problem lies.
  - type: textarea
    id: feature-problem
    attributes:
      label: Feature related to a problem?
      description: |
        A clear and concise description of what the problem or challange is that you'd like to address.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen or a proposed method to solving the problem.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
